export const COUNTRIES = [
  "India",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Oman",
  "Bahrain",
  "Kuwait",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Thailand",
  "Vietnam",
  "Philippines",
  "United Kingdom",
  "United States",
  "Australia",
  "South Africa",
  "Kenya",
  "Nigeria",
  "Egypt",
  "Other",
];
