export const CURRENCIES = [
  { code: "INR", label: "INR (₹) — Indian Rupee" },
  { code: "USD", label: "USD ($) — US Dollar" },
  { code: "EUR", label: "EUR (€) — Euro" },
  { code: "GBP", label: "GBP (£) — British Pound" },
  { code: "AED", label: "AED (د.إ) — UAE Dirham" },
  { code: "SAR", label: "SAR (﷼) — Saudi Riyal" },
  { code: "QAR", label: "QAR (﷼) — Qatari Riyal" },
  { code: "SGD", label: "SGD ($) — Singapore Dollar" },
  { code: "AUD", label: "AUD ($) — Australian Dollar" },
  { code: "CAD", label: "CAD ($) — Canadian Dollar" },
  { code: "JPY", label: "JPY (¥) — Japanese Yen" },
  { code: "CNY", label: "CNY (¥) — Chinese Yuan" },
  { code: "BDT", label: "BDT (৳) — Bangladeshi Taka" },
  { code: "LKR", label: "LKR (Rs) — Sri Lankan Rupee" },
  { code: "NPR", label: "NPR (Rs) — Nepalese Rupee" },
  { code: "MYR", label: "MYR (RM) — Malaysian Ringgit" },
  { code: "IDR", label: "IDR (Rp) — Indonesian Rupiah" },
  { code: "THB", label: "THB (฿) — Thai Baht" },
  { code: "ZAR", label: "ZAR (R) — South African Rand" },
] as const;
